export enum SCREEN_NAME {
  ONBOARDING = 'ONBOARDING',
  SPLASH = 'SPLASH',

  EVENTS_LIST = 'EVENTS_LIST',
  EVENT_DETAIL = 'EVENT_DETAIL',
  EVENT_CREATE = 'EVENT_CREATE',
  EVENT_EDIT = 'EVENT_EDIT',
  EVENTS_PASSED = 'EVENTS_PASSED',

  COLOR_PICKER = 'COLOR_PICKER',
  ICON_PICKER = 'ICON_PICKER',

  WIDGETS_CONFIG = 'WIDGETS_CONFIG',

  PAYWALL = 'PAYWALL',
  PAYMENT_ERROR = 'PAYMENT_ERROR',

  SETTINGS = 'SETTINGS',
  SETTINGS_LANGUAGE = 'SETTINGS_LANGUAGE',
  SETTINGS_NOTIFICATIONS = 'SETTINGS_NOTIFICATIONS',
  ABOUT = 'ABOUT',
  HELP = 'HELP',

  GROUPS = 'GROUPS',
  SHARE_CARD = 'SHARE_CARD',
  SORT_FILTER = 'SORT_FILTER',

  DELETE_CONFIRM = 'DELETE_CONFIRM',
  NOTIF_PERMISSION = 'NOTIF_PERMISSION',
}

export enum STACK_NAME {
  TUNNEL_STACK = 'TUNNEL_STACK',
  CONNECTED_STACK = 'CONNECTED_STACK',
  TAB_NAVIGATOR = 'TAB_NAVIGATOR',
  HOME_STACK = 'HOME_STACK',
  WIDGETS_STACK = 'WIDGETS_STACK',
  SETTINGS_STACK = 'SETTINGS_STACK',
  DETAILS_STACK = 'DETAILS_STACK',
}
