export enum STORAGE_KEY {
  EVENTS = 'EVENTS',
  GROUPS = 'GROUPS',
  USER_PREFERENCES = 'USER_PREFERENCES',
  ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',
  PREMIUM_PURCHASED = 'PREMIUM_PURCHASED',
  LAUNCH_DATE = 'LAUNCH_DATE',
}
